### ISSUE TITLE
Getting 429 back from all requests to Bioconductor

### ISSUE THREAD

**Issue by thomasshouler** [Bioconductor/bioconductor.org#147]
Hello!

Whenever I make any request to Bioconductor, e.g.:
```bash
$ curl -O https://bioconductor.org/packages/3.13/bioc/bin/macosx/contrib/4.1/BiocVersion_3.13.1.tgz -vvv
```

I'm getting a 429 back:
```
< HTTP/1.1 429 Too Many Requests
< Server: CloudFront
< Date: Thu, 10 Mar 2022 16:29:06 GMT
< Content-Length: 0
< Connection: keep-alive
< X-Cache: Error from cloudfront
< Via: 1.1 040f8a2cdffe1cf7a35d28e06c3ed574.cloudfront.net (CloudFront)
< X-Amz-Cf-Pop: IAD89-P1
< X-Amz-Cf-Id: gr3Xb8ZBaIOIzj3lldhc3ReWYzOvZ7V98DdnGXDAOhSnHVGK6sNisw==
```

I was previously making requests to install packages on a schedule and am wondering if perhaps my IP was added to a block list?

**Comment by lshep** [comment]
that seems likely given the error report.   I'm curious at the comment that you were installing packages on a schedule?  For your example you are installing an old release,  packages are not updated -- ever -- so there shouldn't be a need to reinstall anything?  The only packages that are changing are the current release (3.14) and devel (3.15).

**Comment by thomasshouler** [comment]
Hi @lshep -- It was an error in someone's code that was spamming the url. Not intentional. Is there someone I could connect with about seeing if my IP is on a block list and if we could remove it?

**Comment by lshep** [comment]
I can investigate. I would have thought if the script was corrected and you waited a day or two it would reset automatically but I'll investigate more. Could you please send me your IP address? 
I assume then "someone's code" has been corrected and the information regarding old releases and constant re-download has been passed along?  If this was in an existing package please let us know as we should get this corrected as soon as possible and I could reach out with further advice/instructions

**Comment by thomasshouler** [comment]
Thanks @lshep! The code making frequent requests to the url was promptly addressed, and no longer an issue, but we still get 429's even when just making a single request days later.

The requests are getting made from behind a load balancer with IP addresses:
    - 34.233.7.226
    - 52.2.99.157
    - 67.202.50.72
    - 34.194.214.81
    - 34.237.46.85

**Comment by lshep** [comment]
I believe I just removed the IPs from the block list.  Let me know if you have further trouble.
